analyzer:
  language:
    strict-raw-types: false
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
    type_annotate_public_apis: ignore
    public_member_api_docs: ignore
    prefer_relative_imports: ignore
    prefer_function_declarations_over_variables: ignore
    prefer_mixin: ignore
  exclude:
    - "bin/cache/**"
    - "flutter_platform/**"
    - "local_packages/**"

linter:
  rules:
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_catching_errors
    - avoid_catches_without_on_clauses
    - avoid_empty_else
    - avoid_function_literals_in_foreach_calls
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_unnecessary_containers
    - avoid_relative_lib_imports
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_returning_null_for_void
    - avoid_returning_null
    - avoid_returning_this
    - avoid_private_typedef_functions
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    - avoid_types_on_closure_parameters
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - await_only_futures
    - camel_case_types
    - camel_case_extensions
    - cancel_subscriptions
    - constant_identifier_names
    - control_flow_in_finally
    - sort_child_properties_last
    - curly_braces_in_flow_control_structures
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - file_names
    - flutter_style_todos
    - hash_and_equals
    - implementation_imports
    - collection_methods_unrelated_type
    - library_names
    - library_prefixes
    - lines_longer_than_80_chars
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - non_constant_identifier_names
    - overridden_fields
    - only_throw_errors
    - omit_local_variable_types
    - one_member_abstracts
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_final_fields
    - prefer_final_locals
    - prefer_final_in_for_each
    - prefer_foreach
    - prefer_generic_function_type_aliases
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - prefer_spread_collections
    - prefer_single_quotes
    - prefer_typing_uninitialized_variables
    - prefer_null_aware_operators
    - prefer_void_to_null
    - prefer_mixin
    - recursive_getters
    - slash_for_doc_comments
    - sized_box_for_whitespace
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    - type_init_formals
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_statements
    - unnecessary_this
    - unrelated_type_equality_checks
    - unawaited_futures
    - use_to_and_as_if_applicable
    - use_setters_to_change_properties
    - use_rethrow_when_possible
    - valid_regexps
